### ISSUE TITLE
Fix the asset indexer for DAM assets (may no longer be applicable/necessary)

### ISSUE THREAD

**Issue by ericdrosas87** [lsst-epo/craft3-universal-dam-integrator#30]
This is probably no longer needed considering with the new direction we are headed in using the content table we will no longer be extending the base Assets class, nor dealing with volumes, but I wanted to get your two-cents on this first.

**Comment by khalwat** [comment]
Yeah this won't be applicable anymore (which is good!)

**Comment by ericdrosas87** [comment]
Sweet, closing this out!
